# Generated by Django 3.2.5 on 2021-07-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='氏名')),
                ('phone', models.IntegerField(verbose_name='電話番号')),
            ],
        ),
    ]
